apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-redis
  namespace: cache-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-redis
  template:
    metadata:
      labels:
        app: cache-redis
    spec:
      volumes:
      containers:
        - name: redis
          image: redis:7.0.8
          command: ['redis-server']
          ports:
            - containerPort: 6379
