apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "minio"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "bWluaW8="
  rootPassword: "bWluaW8xMjM="