apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: "minio"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
    release: minio