apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mastodon-web
  namespace: mastodon
spec:
  dnsNames:
  - madeinusa.social
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: mastodon-tls