apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
  namespace: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
        - name: smtp
          image: bytemark/smtp:latest
          ports:
            - containerPort: 25
          env:
            - name: MAILNAME
              value: madeinusa.social
